name: 'Delete outdated git tags'
description: 'Deletes git tags that where produced by deleted feature branches.'
author: 'Nils Diekmann'
inputs:
  token:
    description: 'GitHub token for authentication.'
    required: true

runs:
  using: node20
  main: dist/index.js